openapi: 3.0.0
info:
  title: User Search API
  version: 1.0.0
  description: API to search users by username or user_id.

servers:
  - url: http://0.0.0.0:8889
    description: Local server

paths:
  /search_user:
    get:
      summary: Search user by username
      description: Retrieve user information by searching with a partial or full username.
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
          description: The username to search for.
      responses:
        "200":
          description: A list of users matching the search criteria.
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        user_id:
                          type: integer
                        username:
                          type: string
                        email:
                          type: string
                        first_name:
                          type: string
                        last_name:
                          type: string
                        phone_number:
                          type: string
                        address:
                          type: string
                        created_at:
                          type: string
                          format: date-time
        "400":
          description: Bad Request - Username parameter is required.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "username parameter is required"
        "500":
          description: Server Error - Issue querying the database.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error: Database connection error"

  /search_user_by_id:
    get:
      summary: Search user by user ID
      description: Retrieve user information by user ID.
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: integer
          description: The unique ID of the user.
      responses:
        "200":
          description: A list of users matching the search criteria (should contain one user).
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        user_id:
                          type: integer
                        username:
                          type: string
                        email:
                          type: string
                        first_name:
                          type: string
                        last_name:
                          type: string
                        phone_number:
                          type: string
                        address:
                          type: string
                        created_at:
                          type: string
                          format: date-time
        "400":
          description: Bad Request - User ID parameter is required.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "user_id parameter is required"
        "500":
          description: Server Error - Issue querying the database.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Error: Database connection error"
